<a href="https://colab.research.google.com/github/tathagata-raha/nlp_project/blob/master/Project_gru.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install conll-df

  ERROR: Failed building wheel for conll-df
  Running setup.py clean for conll-df
Failed to build conll-df
    Running setup.py install for conll-df ... done


In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
from keras.preprocessing.sequence import pad_sequences


Using TensorFlow backend.


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import pandas as pd
from conll_df import conll_df
path = '/content/drive/My Drive/hind.conllu'
df = conll_df(path, file_index=False)

In [0]:
curr = 1
arr =  []
newArr = []
sentArray = []
tagArray = []
sentnew =[]
tagnew=[]
for i in df.itertuples(): 
  if(curr>1000):
    break
  if(i[0][0]>curr):
    #print(curr)
    arr.append([j for j in newArr])
    sentArray.append([j for j in sentnew])
    tagArray.append([j for j in tagnew])
    curr+=1
    newArr = []
  else:
    newArr.append((i[1],i[3]))
    sentnew.append(i[1])
    tagnew.append(i[3])



In [0]:
(train_sentences, 
 test_sentences, 
 train_tags, 
 test_tags) = train_test_split(sentArray, tagArray, test_size=0.2)
 


In [0]:
words, tags = set([]), set([])
 
for s in train_sentences:
    for w in s:
        words.add(w.lower())
 
for ts in train_tags:
    for t in ts:
        tags.add(t)
 
word2index = {w: i + 2 for i, w in enumerate(list(words))}
word2index['-PAD-'] = 0  # The special value used for padding
word2index['-OOV-'] = 1  # The special value used for OOVs
 
tag2index = {t: i + 1 for i, t in enumerate(list(tags))}
tag2index['-PAD-'] = 0  # The special value used to padding
 

In [10]:
train_sentences_X, test_sentences_X, train_tags_y, test_tags_y = [], [], [], []
 
for s in train_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w.lower()])
        except KeyError:
            s_int.append(word2index['-OOV-'])
 
    train_sentences_X.append(s_int)
 
for s in test_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w.lower()])
        except KeyError:
            s_int.append(word2index['-OOV-'])
 
    test_sentences_X.append(s_int)
 
for s in train_tags:
    train_tags_y.append([tag2index[t] for t in s])
 
for s in test_tags:
    test_tags_y.append([tag2index[t] for t in s])
 
print(train_sentences_X[0])
print(test_sentences_X[0])
print(train_tags_y[0])
print(test_tags_y[0])

[1951, 824, 3011, 1343, 799, 445, 3318, 558, 1163, 2682, 978, 3639, 749, 1812, 325, 825, 978, 2391, 2889, 3079, 2353, 2682, 978, 893, 1610, 812, 2754, 826, 141, 1824, 3318, 13, 3453, 280, 2576, 2391, 2889, 812, 978, 306, 802, 2594, 2682, 978, 2401, 207, 515, 1671, 1078, 1652, 3483, 390, 3453, 1139, 1207, 888, 1991, 2682, 978, 204, 3453, 1459, 799, 2879, 3453, 504, 3435, 3550, 1078, 1951, 2594, 2823, 3515, 1841, 3453, 2727, 1078, 2682, 1457, 2080, 1841, 31, 1966, 1175, 825, 978, 3358, 2754, 847, 2201, 1078, 2851, 1947, 2682, 978, 1458, 3011, 652, 2809, 3277, 2682, 978, 2154, 558, 1951, 2882, 2201, 2754, 68, 2201, 1078, 1344, 2682, 978, 3395, 1423, 1812, 1594, 2562, 2682, 978, 1803, 3318, 1411, 2120, 2884, 3453, 542, 3298, 3677, 1078, 3620, 815, 1982, 2754, 31, 3712, 1780, 2682, 978, 3659, 1163, 2201, 2151, 76, 2201, 115, 76, 1633, 1689, 3453, 280, 745, 76, 1163, 1322, 76, 3133, 2754, 2028, 1620, 76, 3056, 1536, 76, 2816, 1432, 1078, 1741, 76, 3517, 2754, 1386, 649, 2151, 31, 812, 978, 3

In [11]:

MAX_LENGTH = len(max(train_sentences_X, key=len))
print(MAX_LENGTH) 

16562


In [12]:
train_sentences_X = pad_sequences(train_sentences_X, maxlen=MAX_LENGTH, padding='post')
test_sentences_X = pad_sequences(test_sentences_X, maxlen=MAX_LENGTH, padding='post')
train_tags_y = pad_sequences(train_tags_y, maxlen=MAX_LENGTH, padding='post')
test_tags_y = pad_sequences(test_tags_y, maxlen=MAX_LENGTH, padding='post')
 
print(train_sentences_X[0])
print(test_sentences_X[0])
print(train_tags_y[0])
print(test_tags_y[0])


[1951  824 3011 ...    0    0    0]
[1951  824 3011 ...    0    0    0]
[13 15  1 ...  0  0  0]
[13 15  1 ...  0  0  0]


In [15]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, InputLayer, Bidirectional, TimeDistributed, Embedding, Activation, GRU
from keras.optimizers import Adam
 
 
model = Sequential()
model.add(InputLayer(input_shape=(MAX_LENGTH, )))
model.add(Embedding(len(word2index), 128))
model.add(GRU(256, return_sequences=True))
model.add(TimeDistributed(Dense(len(tag2index))))
model.add(Activation('softmax'))
 
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(0.001),
              metrics=['accuracy'])
 
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 16562, 128)        476288    
_________________________________________________________________
gru_1 (GRU)                  (None, 16562, 256)        295680    
_________________________________________________________________
time_distributed_2 (TimeDist (None, 16562, 16)         4112      
_________________________________________________________________
activation_2 (Activation)    (None, 16562, 16)         0         
Total params: 776,080
Trainable params: 776,080
Non-trainable params: 0
_________________________________________________________________


In [0]:
def to_categorical(sequences, categories):
    cat_sequences = []
    for s in sequences:
        cats = []
        for item in s:
            cats.append(np.zeros(categories))
            cats[-1][item] = 1.0
        cat_sequences.append(cats)
    return np.array(cat_sequences)

In [17]:
cat_train_tags_y = to_categorical(train_tags_y, len(tag2index))
print(cat_train_tags_y[0])

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [21]:
model.fit(train_sentences_X, to_categorical(train_tags_y, len(tag2index)), batch_size=20, epochs=2, validation_split=0.2)


Train on 640 samples, validate on 160 samples
Epoch 1/2


ResourceExhaustedError: ignored

In [0]:
scores = model.evaluate(test_sentences_X, to_categorical(test_tags_y, len(tag2index)))
print(f"{model.metrics_names[1]}: {scores[1] * 100}")   
 

In [0]:
test_samples = [
    "रामायण काल में भगवान राम के पुत्र कुश की राजधानी कुशावती को 483 ईसा पूर्व बुद्ध ने अपने अंतिम विश्राम के लिए चुना ।".split(),
    "मल्‍लों की राजधानी होने के कारण प्राचीनकाल में इस स्‍थान का अत्‍यंत महत्‍व था ।".split()
]
print(test_samples)

In [0]:
test_samples_X = []
for s in test_samples:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w.lower()])
        except KeyError:
            s_int.append(word2index['-OOV-'])
    test_samples_X.append(s_int)
 
test_samples_X = pad_sequences(test_samples_X, maxlen=MAX_LENGTH, padding='post')
print(test_samples_X)
 

In [0]:
predictions = model.predict(test_samples_X)
print(predictions, predictions.shape)

In [0]:
def logits_to_tokens(sequences, index):
    token_sequences = []
    for categorical_sequence in sequences:
        token_sequence = []
        for categorical in categorical_sequence:
            token_sequence.append(index[np.argmax(categorical)])
 
        token_sequences.append(token_sequence)
 
    return token_sequences

In [22]:
print(logits_to_tokens(predictions, {i: t for t, i in tag2index.items()}))


NameError: ignored

Making accuracy metric to ignore padding tokens 

In [0]:

from keras import backend as K
 
def ignore_class_accuracy(to_ignore=0):
    def ignore_accuracy(y_true, y_pred):
        y_true_class = K.argmax(y_true, axis=-1)
        y_pred_class = K.argmax(y_pred, axis=-1)
 
        ignore_mask = K.cast(K.not_equal(y_pred_class, to_ignore), 'int32')
        matches = K.cast(K.equal(y_true_class, y_pred_class), 'int32') * ignore_mask
        accuracy = K.sum(matches) / K.maximum(K.sum(ignore_mask), 1)
        return accuracy
    return ignore_accuracy
 

In [24]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, InputLayer, Bidirectional, TimeDistributed, Embedding, Activation, GRU
from keras.optimizers import Adam
 
 
model = Sequential()
model.add(InputLayer(input_shape=(MAX_LENGTH, )))
model.add(Embedding(len(word2index), 128))
model.add(GRU(256, return_sequences=True))
model.add(TimeDistributed(Dense(len(tag2index))))
model.add(Activation('softmax'))
 
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(0.001),
              metrics=['accuracy', ignore_class_accuracy(0)])
 
model.summary()
 

SyntaxError: ignored

In [0]:
model.fit(train_sentences_X, to_categorical(train_tags_y, len(tag2index)), batch_size=20, epochs=3, validation_split=0.2)


In [0]:
predictions = model.predict(test_samples_X)
print(logits_to_tokens(predictions, {i: t for t, i in tag2index.items()}))